package me.misha2win.scracesmpplugin.util;

import java.util.ArrayList;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.data.BlockData;

public class StructureHandler {

	public static ArrayList<BlockData[][][]> structures = new ArrayList<>();

	public static void placeStructure(int structureIndex, World w, double x, double y, double z) {
		if (structureIndex < structures.size()) {
			BlockData[][][] strctr = structures.get(structureIndex);

			for (int i = 0; i < strctr.length; i++) {
				for (int j = 0; j < strctr[0].length; j++) {
					for (int k = 0; k < strctr[0][0].length; k++) {
						new Location(w, x + i, y + j, z + k).getBlock().setBlockData(strctr[i][j][k]);
					}
				}
			}
		}
	}

	public static BlockData[][][] createString(World w, double x1, double y1, double z1, double x2, double y2,
			double z2) {
		int deltaX = (int) (x1 - x2);
		int deltaY = (int) (y1 - y2);
		int deltaZ = (int) (z1 - z2);

		int x = (int) Math.min(x1, x2);
		int y = (int) Math.min(y1, y2);
		int z = (int) Math.min(z1, z2);

		BlockData[][][] result = new BlockData[Math.abs(deltaX) + 1][Math.abs(deltaY) + 1][Math.abs(deltaZ) + 1];

		String str = "int counter = 0;\n"
				+ "for (int i = 0; i <= " + Math.abs(deltaX) + "; i++) {\n" 
				+ "\tfor (int j = 0; j <= " + Math.abs(deltaY) + "; j++) {\n" 
				+ "\t\tfor (int k = 0; k <= " + Math.abs(deltaZ) + "; k++) {\n" 
				+ "\t\t\tnew Location(world, x + i, y + j, z + k).getBlock().setBlockData(Bukkit.getServer().createBlockData(bd[counter]));\n" 
				+ "\t\t\tcounter++;\n" 
				+ "\t\t}\n" 
				+ "\t}\n" 
				+ "}";

		String str2 = "String[] bd = new String[] {\n";
		for (int i = 0; i <= Math.abs(deltaX); i++) {
			for (int j = 0; j <= Math.abs(deltaY); j++) {
				for (int k = 0; k <= Math.abs(deltaZ); k++) {
					Location loc = new Location(w, x + i, y + j, z + k);
					Block block = loc.getBlock();
					result[i][j][k] = block.getBlockData();

					str2 += "\t\"" + block.getBlockData().getAsString() + "\"";
					if (i == Math.abs(deltaX) && j == Math.abs(deltaY) && k == Math.abs(deltaZ)) {
						str2 += "\n};";
					} else {
						str2 += ",\n";
					}
				}
			}
		}

		Bukkit.getLogger().info("\n" + str2 + "\n\n" + str);

		return result;
	}

	public static void placeETableStructure(World world, double x, double y, double z) {
		String[] bd = getBlocks();
		
		// Structure size: (13, 23, 13)
		// Execute at: -6, -18, -6

		int counter = 0;
		for (int i = 0; i <= 12; i++) {
			for (int j = 0; j <= 22; j++) {
				for (int k = 0; k <= 12; k++) {
					BlockData block = Bukkit.getServer().createBlockData(bd[counter]);
					new Location(world, x + i, y + j, z + k).getBlock().setBlockData(block);
					
					if (bd[counter].equals("minecraft:enchanting_table")) {
						System.out.println("Enchanting table is at " + (int)(x + i) + ", " + (int)(y + j) + ", " + (int)(z + k) + "!");
					}
					
					counter++;
				}
			}
		}
	}

	public static String[] getBlocks() {
		return new String[] { "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:verdant_froglight[axis=y]",
				"minecraft:verdant_froglight[axis=y]", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:verdant_froglight[axis=y]",
				"minecraft:verdant_froglight[axis=y]", "minecraft:sculk", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:verdant_froglight[axis=z]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:verdant_froglight[axis=z]", "minecraft:sculk", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=double]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tiles", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=inner_right]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=inner_left]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=double]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:sculk_shrieker[can_summon=false,shrieking=false]", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk_shrieker[can_summon=false,shrieking=false]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=inner_left]",
				"minecraft:verdant_froglight[axis=y]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:verdant_froglight[axis=y]",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=inner_right]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:obsidian", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:obsidian", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:obsidian",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:obsidian", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:obsidian", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:enchanting_table", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=double]",
				"minecraft:deepslate_tile_slab[type=double]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=double]",
				"minecraft:deepslate_tile_slab[type=double]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:sculk_shrieker[can_summon=false,shrieking=false]", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk_shrieker[can_summon=false,shrieking=false]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=inner_right]",
				"minecraft:verdant_froglight[axis=y]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:verdant_froglight[axis=y]",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=inner_left]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk",
				"minecraft:black_stained_glass", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:sculk", "minecraft:black_stained_glass", "minecraft:black_stained_glass",
				"minecraft:black_stained_glass", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:deepslate_tiles",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tiles", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=inner_left]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=inner_right]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=double]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:verdant_froglight[axis=z]",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:verdant_froglight[axis=z]",
				"minecraft:sculk", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=outer_left]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=outer_left]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight]", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight]", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=double]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:verdant_froglight[axis=y]",
				"minecraft:verdant_froglight[axis=y]", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:verdant_froglight[axis=y]",
				"minecraft:verdant_froglight[axis=y]", "minecraft:sculk", "minecraft:air",
				"minecraft:deepslate_tile_stairs[facing=south,half=top,shape=outer_right]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight]", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight]",
				"minecraft:deepslate_tile_stairs[facing=west,half=top,shape=outer_right]", "minecraft:air",
				"minecraft:air", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:deepslate_tile_slab[type=bottom]", "minecraft:deepslate_tile_slab[type=bottom]",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:deepslate_tiles",
				"minecraft:deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:sculk", "minecraft:sculk",
				"minecraft:sculk", "minecraft:sculk", "minecraft:sculk", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air",
				"minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air" };
	}

	public static void main(String[] args) {
		String[] bd = getBlocks();

		ArrayList<String> strs = new ArrayList<>();
		strs.add(bd[0]);

		int totalSkips = 0;
		int skip = 1;
		for (int i = 1; i < bd.length; i++) {
			if (strs.get(i - 1 - totalSkips).equals(bd[i])) {
				totalSkips++;
				skip++;
			} else {
				if (skip > 1) {
					strs.add(i - 1 - totalSkips, strs.remove(i - 1 - totalSkips) + " " + skip);
					skip = 1;
				}
				strs.add(bd[i]);
			}
		}

		// System.out.println(strs);

		String s = "{ ";
		for (String str : strs) {
			s += "\"" + str + "\", ";
		}
		s += "}";
		System.out.println(s);

		System.out.println("bd length: " + bd.length);
		System.out.println("strs length: " + strs.size());
		
		placeETableStructure(null, -6, -18, -6);
	}

}
