name: ScarceLifeSmp
version: 2.1
author: Misha2win
main: me.misha2win.scracesmpplugin.ScarceLife
description: the plugin for the ScarceLifeSmp
api-version: '1.21.11'

commands:

  givelife:
    description: gives one of your lives to another player
    usage: "Usage: /givelife (player)"

  givescarce:
    description: gives a scarce item to the recipient
    usage: "Usage: /givescarce [player] [item] [count]"

  scarceconfig:
    description: command for setting or getting config values
    usage: "Usage: /scarceconfig (get | set) (config) [value to set]"

  scarce:
    description: admin command for testing features
    usage: "Usage: /scarce (give | gamemode)"

  life:
    description: edits the amount of lives players have
    usage: "Usage: /life (add | remove | set) (player | all) (number)"

  tpaccept:
    description: accepts an incoming teleport request
    usage: "Usage: /tpaccept [player]"

  tpcancel:
    description: cancels a pending teleport request
    usage: "Usage: /tpcancel"

  tpdeny:
    description: denies an incoming teleport request
    usage: "Usage: /tpdeny [player]"

  tpa:
    description: allows a dead player to teleport to another player!
    usage: "Usage: /tpa (player)"
